### ISSUE TITLE
Fixing PCLZIP error on WP Rocket update

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1988]
Sometimes when we try to update WP Rocket we get this error: 

```
Update Failed: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature
```

@webtrainingwheels observed that one of the reasons why this happens is when the version set on the user profile is lesser than the version specified on the update notification. 

For example, update notification will prompt to update to 3.4, while the version in the user profile will be 3.3.7

@alfonso100 had a test site where the issue could be replicated. @Tabrisrp dug deeper and found multiple issues that could be causing this. 

This apparently needs fixes on the update-notifications end by @GeekPress and then on the plugin end. 

Related conversations: 

- https://wp-media.slack.com/archives/C08N8J6VC/p1569611238066700

**Comment by GeekPress** [comment]
I closed it as it has been fixed and it depends to the website ^^

**Comment by ensemblebd** [comment]
For anyone else who is encountering, and finds the above to be lacking in let's say, brevity... 
Have had this issue going on a year, possibly longer. Rocket support suggested previously to us rather to wait for new update which should solve, but no. 
Let's try digging, which is the only way to actually solve problems. You don't just say "oh well things cause this". No, you dig, you find answer, and you report it. Ideally publicly, not in a private slack channel. 

I added the following to wp-admin/includes/class-pclzip.php @ line 217:
```
copy($p_zipname, 'C:\\inetpub\\wwwroot\\test.zip');
```
Which produces curiously 1 kilo. Edited the "zip" with notepad, and saw:  
```
BAD_CONSUMERKEY
```
Perfect now that makes sense. It tried to download wp rocket, but with a bad token, rocket website security says "no you haven't paid for it". Except we did, cause how else did we install wp rocket. 
So now let's find out why.

Although plugin is clearly using wordpress libs, the server is custom, so by scanning through /inc/admin/upgrader.php , it would seem `consumer_key` by way of `get_rocket_option` is of importance. GREP scanning revealed also `WP_ROCKET_KEY` global. 
I must presume that when we download Rocket from the website UI itself after purchasing, it has code to inject the key into main file.  `class-wp-rocket-requirements-check` appears to have logistics to slip WP_ROCKET_KEY back into `consumer_key` option. 
So in theory, we just need to define('WP_ROCKET_KEY', 'my_api_key') to resolve.
I noticed the way they handle this, is with a file called "license-data.php" in the root folder of plugin.
Interesting. That file is missing from server.   
_(Note, you can also get your api key by chrome inspecting your download link on dashboard. It's the hex-looking alpha numeric after final slash in url of green button)_
Seemed to me easiest fix is likely to copy `license-data.php` to the server, and let that trickle through the system again. 
But let's not stop there. That would be a lazy man's fix and would presume it would even fix anything.

Let's see what's in the database, surely that value was set at time of initial install, after which rocket deleted our license file presumably for security reasons. 
`SELECT * FROM `web_options` WHERE option_name LIKE '%rocket%'`
Alrighty `wp_rocket_settings` deserialize(), looks like you have `consumer_key` right there, ready for usage. 
Wonder why rocket is failing to dispatch that. We'd have to log or Wireshark the Curl requests to find that out. 
Seems easier to poke at it with a **long** stick...

GREP scan again seems to show the only use case of `consumer_key` of value, would be under `class-updater-api-common-subscriber.php`, which would mean they are authenticating us by way of a user agent!? strange.
This takes us to `maybe_set_rocket_user_agent`. Line 131. 
```
file_put_contents('C:\\inetpub\\wwwroot\\log.log', $url . '|' .$this->api_host. '|' . json_encode($request)."\r\n", FILE_APPEND);
```
resulting in: 
```
https://wp-rocket.me/<CONSUMER_KEY>/wp-rocket_3.7.5.zip|
wp-rocket.me|
{
  "method": "GET",
  "timeout": 300,
  "redirection": 5,
  "httpversion": "1.0",
  "user-agent": "WordPress\/5.4.4; https:\/\/mywebsite.net;WP-Rocket|3.5.4|<CONSUMER_KEY>|<CONSUMER_EMAIL>|https:\/\/mywebsite.net|7.3;",
  "reject_unsafe_urls": true,
  "blocking": true,
  "headers": [
    
  ],
  "cookies": [
    
  ],
  "body": null,
  "compress": false,
  "decompress": true,
  "sslverify": true,
  "sslcertificates": "C:\\inetpub\\wwwroot\/wp-includes\/certificates\/ca-bundle.crt",
  "stream": true,
  "filename": "C:\\Windows\\TEMP\/wp-rocket_3.7.5-NONvHR.tmp",
  "limit_response_size": null
}
```
Alright good to know, the user-agent is only used for them to track info about the site using it. Primary auth is simply in the URL path (route prefix of consumer_key).
It's a GET request, so let's throw it in postman, browser test revealed UA pairing is required. 
And whattayaknow... `BAD_CONSUMERKEY`.

So inspecting the key itself, and comparing to what is on file when logging into dashboard of wp-rocket, it is **clear** that the license key has changed. 
I can only presume at some point a year ago my company upgraded from personal (the one i paid for myself), to the unlimited edition. At which point all existing sites have an invalid legacy key which is expired.

_I think my frustration was evident in my words, so I won't further digress. Don't get me wrong, i LOVE wp-rocket. But guys.
Perhaps one of your employees could have spent 30 minutes doing what I did, no? 
And further, could you not tell that by looking at failed request logs per our user accounts during ticket submission?
Invalid license key requests should be pretty high up on your security/fraud list; one would think._

---------------------------------------------------

#### The answer is simple. Update your license. 
You can do it several ways (I have personally tested each of these, and confirmed 100%):

1.  **Noobie**: Download wp-rocket.zip, extract, copy & paste `license-data.php` to your server's plugin root folder of rocket. Click Update in plugins page. 
2. **Hacker**: edit wp-config.php and put: `define('WP_ROCKET_KEY', '<your key>');` above the final include. Click Update in plugins page, and remove this line later to cleanup.
3. **Slasher**: Run a deserialize() serialize() script and adjust the object's value of ->consumer_key , for the get_option('wp_rocket_settings'), then set_option.
4. **DB Admin**:  run `UPDATE wp_options SET option_value = REPLACE(option_value, 'old_key', 'new_key') WHERE option_name = 'wp_rocket_settings'`.  I would presume this is unsafe, so I don't recommend. But the license key hashes appear to be the same length to me, which would mean it won't break serialization.  Note the table prefix. 
- perhaps WP Rocket could provide a fix in their code to allow user to refresh their license easily. Or provide a helper plugin with one of the above inside. Or at the least... better error reporting. 

My company has many websites, so I opted for fix # 2 .

**Comment by arunbasillal** [comment]
@Tabrisrp Please note the previous comment ^

@ensemblebd The frustration is clear, sorry about that. But we figured this was over. Thanks for the details 👍

**Comment by addedlovely** [comment]
Am also now seeing this on multiple sites, our license key is unchanged and valid.

Upgrading from version 3.16.2.1 to 3.16.3 

license-data.php is present in the existing plugin and matches the data in the v3.16.3  ( when downloaded from the 'my account' area on wp-rocket.me

Added define( 'WP_ROCKET_KEY', 'xxxx'); to wp-config.php does not resolve it for me.
