### ISSUE TITLE
3.6.2: Include media attribute when loading CSS files async

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2885]
This is related to the new method for loading CSS files asynchronously with the Optimize CSS Delivery option, introduced in 3.6.2.

We need to account for the @media attribute when we load the CSS files. 

Related ticket: https://secure.helpscout.net/conversation/1220486412/179297?folderId=377611

Here the customer is using the Avada theme. Many of their files are using specific media attributes, e.g.: 
`media='only screen and (min-width: 784px) and (max-width: 856px)'`

When these are preloaded without the correct media attribute, it causes additional HTTP requests. 
Problem can be seen in these test results: https://secure.helpscout.net/conversation/1220486412/179297?folderId=377611#thread-3499389455

Per @hellofromtonya :

> For each stylesheet, we now do the following:
> Add a `<link rel="stylesheet" href="" as="style">`   - This doesn’t include the @media attribute.
> Modify the original <link> ’s onload and media to make it async.
> The first one needs the media attribute too.

**Comment by hellofromtonya** [comment]
Fixed in this commit https://github.com/wp-media/wp-rocket/pull/2868/commits/7f3cd313650a2801bb2d82d7fc8ba4090ba977f1. Will be part of 3.6.2.1

**Comment by Davidacu** [comment]
So originally we were creating 2 `<link>` for each stylesheet, one that has the `preload` attribute, and the second `<link>` has the `media=print`. => https://i.imgur.com/tqfm7UB.png

now we are still doing 2 `<link>` for each stylesheet, the one with `preload` attribute now preserves the original media attribute, however we are still adding the second `<link>` with the `media=print` which makes the browser download the stylesheet.
=> https://i.imgur.com/sVQo86n.png

Shouldn't we get rid of the `<link>` that has `media=print` for those stylesheets that already have a `media` attribute set?

**Comment by hellofromtonya** [comment]
>Shouldn't we get rid of the <link> that has media=print for those stylesheets that already have a media attribute set?

@Davidacu No, it's correct. Let me explain the how, why, and when.

Let's say the web page has this stylesheet:

```html
<link rel="stylesheet" type="text/css" href="https://example.org/file1.css" media="screen and (max-width: 600px)">
```

When the Optimize CSS Delivery option is turned on, we convert it into this:

```html
<link rel="preload" href="https://example.org/file1.css" as="style" media="screen and (max-width: 600px)">
<link rel="stylesheet" type="text/css" href="https://example.org/file1.css" media="print" onload="this.onload=null;this.media='screen and (max-width: 600px)'">
```

and add the original link into a `<noscript>` inserted just above the closing body `</body>` tag.

Why? To load the stylesheet asynchronously which improves the page loading performance by allowing a browser to continue processing instead of waiting for the stylesheet to be downloaded from the server.

How do we do that? But let's break it down here.

The original stylesheet link has a `media="screen and (max-width: 600px)"` which means:

- Targets smaller screens (phones or when the browser is scaled down). 
- On screens where it's larger than 600px, the browser will not request the resource (stylesheet) from the server and will not load it.

To load it asynchronously, we:

- Change the `media` attribute's value to `'print'`
Why? `media="print"` is for when you are printing something, not displaying it in the browser. The browser knows that the target is the screen. It detects the "print" value and skips over it, not loading the stylesheet.
- Add an `onload` attribute with the original `media` value. 
Why? When the `onload` event fires, then a little JavaScript happens to change the `media` value back to its original value. Now the browser will request and load it.

That looks like this:

```html
<link rel="stylesheet" type="text/css" href="https://example.org/file1.css" media="print" onload="this.onload=null;this.media='screen and (max-width: 600px)'">
```

What about the `"preload"` link? 

`rel="preload"` is not well supported by all browsers. Some modern browsers do support it. For those modern browsers, we add this extra link:

```html
<link rel="preload" href="https://example.org/file1.css" as="style" media="screen and (max-width: 600px)">
```

This link tells the browser to:

- Fetch (request) the stylesheet resource from the web host server
- When the screen is smaller than 600px width

But notice it's just a preload and not a stylesheet, i.e. by the `rel` attribute. This link element does not load the stylesheet. Rather, it speeds up the fetching/downloading process so that the stylesheet is ready and available for loading later.

@Davidacu Does that make sense?

**Comment by Davidacu** [comment]
Ok yes, it makes sense, however, I'm not seeing any difference after the fix in the amount of CSS downloaded resources when inspecting the requests in the network pane with the developer tools.
http://sc.com.ly/show/j09scBzUO7MDpCJbvPTW1GkqLE2dnRHQ

Or when analyzing at gtmetrix:
31 downloaded CSS files before the fix https://gtmetrix.com/reports/mega.wp-rocket.me/TcenrQDO
31 downloaded CSS files after the fix https://gtmetrix.com/reports/mega.wp-rocket.me/C5MGynmZ

**Comment by Davidacu** [comment]
now with 3.6.1 -> 6 downloaded CSS files https://gtmetrix.com/reports/mega.wp-rocket.me/IRzJq7zX
so in 3.6.2, and after the fix we download the same 31 files, so we're still missing something.

**Comment by Tabrisrp** [comment]
From what I'm reading here: https://css-tricks.com/why-browsers-download-stylesheets-with-non-matching-media-queries/

It's expected for the browser to download all stylesheets, even though they don't match the current display, to account for resizing the window.

I'm wondering if what we had before (only the `preload`) was incorrect, and resulted unexpectedly in some CSS files not being downloaded?

**Comment by Davidacu** [comment]
I will also like to point out that comparing the blocking time shown from the waterfall in the gtmetrics reports,
we can see that before the fix the blocking time for downloading the CSS was less then what it is now.
before the fix, it was in average `320ms`
and after the fix an average of `580ms`

**Comment by Tabrisrp** [comment]
Closing this as we reverted from this method, and we are likely not going to revisit it in the future.
