### ISSUE TITLE
Regex gets stripped as comment in minified JS file

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#2974]
Two double slashes in Regex can be interpreted as comment markers -- even though the first one is escaped -- and subsequent JS is then stripped from the resulting minified file.

i.e., it starts out like this:

```
if(b)return w.IGNORE;var c=B(fb(a,"href"));b=R(fb(a,"hostname"));c=c?/^https?:\/\//.test(c)||/^\/\//.test(c):!1;if(c&&!lc(a)){if(la)return w.TRACK;
if(!0===p.aff_domains[b]||H(lb,b))return w.AFFILIATE;if(Ka(b))return w.PRE_AFFILIATED;
```

but it ends up like this:

```
if(b)return w.IGNORE;var c=B(fb(a,"href"));b=R(fb(a,"hostname"));c=c?/^https?:\/\
if(!0===p.aff_domains[b]||H(lb,b))return w.AFFILIATE;if(Ka(b))return w.PRE_AFFILIATED;
```

(Note that in the original ticket, this code was contained within an external file, so the problem didn't become apparent until Combine JS was enabled.) 

Steps to reproduce:

1. Upload the attached _.txt_ file to your theme folder, then rename it to have a _.js_ extension.
2. Enqueue the file via your theme's _functions.php_.
3. Enable JS minification in WP Rocket (but not Combine JS, to make the next step easier).
4. Inspect the final code in the resulting minified file, to see how it's changed.

Related issues from the third party minify library repo:
* https://github.com/matthiasmullie/minify/issues/323
* https://github.com/matthiasmullie/minify/issues/329

Pull request which might be the fix:
https://github.com/matthiasmullie/minify/pull/330

Original ticket: https://secure.helpscout.net/conversation/1241574590/183879
Slack discussion: https://wp-media.slack.com/archives/C43T1AYMQ/p1596652561163300

[166124X1633667.skimlinks.txt](https://github.com/wp-media/wp-rocket/files/5045415/166124X1633667.skimlinks.txt)

**Comment by enricodias** [comment]
I just updated the PR matthiasmullie/minify#330 to include this case, but it I don't know when (and if) it will be merged.

**Comment by jazir555** [comment]
I have a feeling this is deeply related to the Elementor JS file loading issue. I'm not a coder, but it likely that this could be a reason WP-Rocket is ignoring those files being dequeued with the new elementor asset loading experiment enabled. The feature is explicitly for JS files.

**Comment by Mai-Saad** [comment]
Can reproduce it on trunk by adding `if(b)return w.IGNORE;var c=B(fb(a,"href"));b=R(fb(a,"hostname"));c=c?/^https?:\/\//.test(c)||/^\/\//.test(c):!1;if(c&&!lc(a)){if(la)return w.TRACK;
if(!0===p.aff_domains[b]||H(lb,b))return w.AFFILIATE;if(Ka(b))return w.PRE_AFFILIATED;` in js file used in template .. fixed on the related branch but if we added space after // the problem will still exist.
@Tabrisrp shouldn't we handle this case? `if(b)return w.IGNORE;var c=B(fb(a,"href"));b=R(fb(a,"hostname"));c=c?/^https?:\/\// .test(c)||/^\/\//.test(c):!1;if(c&&!lc(a)){if(la)return w.TRACK;
if(!0===p.aff_domains[b]||H(lb,b))return w.AFFILIATE;if(Ka(b))return w.PRE_AFFILIATED;`

**Comment by remyperona** [comment]
No we don't need to handle this case

**Comment by remyperona** [comment]
Reopening as the change is creating unwanted side effects, described in PR #4192

**Comment by weotch** [comment]
I ran into this myself.  In my case WP Rocket is acting on an already minified JS file.  The source regex comes [from here](https://github.com/amplitude/ua-parser-js/blob/9999815ac8c969306594c650566695fba3506830/src/ua-parser.js#L450
).  Here is a snippet from the minified state, pre-WP Rocket.  Note the `\sbuild\/.+silk\` part:

```js
[/(kf[A-z]+)\sbuild\/.+silk\//i],[o,[a,"Amazon"],[s,f]],[/(sd|kf)[0349hijorstuw]+\sbuild\/.+silk\//i],[[o,h.str,d.device.amazon.model]
```

After this JS is ran through WP Rocket, the `//` and everything after gets truncated:

```js
[/(kf[A-z]+)\sbuild\/.+silk\
```

**Comment by piotrbak** [comment]
This one needs to be fixed on the library side. We'll update the library when the fix is released.
