### ISSUE TITLE
Delay JS can trigger Content Security Policy issues

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#3086]
On a customer’s site, the Delay JS option is causing this error:
`Content Security Policy: The page's settings blocked the loading of a resource at data:text/javascript;base64,CgkJCShmdW5j… ("script-src").`

Ticket: https://secure.helpscout.net/conversation/1277725267/193440?folderId=377611
Slack: https://wp-media.slack.com/archives/C43T1AYMQ/p1599698949098900

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
@webtrainingwheels Can you please add the `steps to reproduce` if you can find them? We can then send this to our developers for grooming.

**Comment by hellofromtonya** [comment]
@engahmeds3ed Can you help out here by adding the steps to reproduce please?

**Comment by sandyfigueroa** [comment]
Same issue here: https://secure.helpscout.net/conversation/1289115268/196711/

It seems that _data:_ is not recognized as a secure source for resources. For this user I recommended adding _data:_ to the script-src CPS: 

`
script-src 'self' data:;
`
And it worked very well according to the user.

**Comment by sandyfigueroa** [comment]
Additional information:

To **reproduce the issue**, the only requirement I saw, was that a CSP was declared without _data:_ as a secure source for script-src, example (.htaccess):

`
<IfModule mod_headers.c>
Header set Content-Security-Policy "default-src 'self' ; img-src 'self' data: http: https: ; script-src 'self' *.opcionesbinarias.site  'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' http: https: ; font-src 'self' data: https: http:  ; frame-src https://staticxx.facebook.com/ http: https: ; base-uri 'self' ;object-src 'none';"
</IfModule>
`

And adding _data:_ the issue was resolved:

`
<IfModule mod_headers.c>
Header set Content-Security-Policy "default-src 'self' ; img-src 'self' data: http: https: ; script-src 'self' data: *.opcionesbinarias.site  'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' http: https: ; font-src 'self' data: https: http:  ; frame-src https://staticxx.facebook.com/ http: https: ; base-uri 'self' ;object-src 'none';"
</IfModule>
`

**Comment by GeekPress** [comment]
With our new Delay JS option scheduled for 3.9, this problem will be automatically fixed. So I'm closing this issue.

**Comment by devendrabhandari** [comment]
After adding a **nonce** to the Content Security Policy (CSP) and inline JavaScript code, the WP Rocket Delay JavaScript is triggering the following CSP issues only in the Firefox browser:

`Content Security Policy: The page's settings blocked the loading of a resource at`

After debugging, we found that the error is thrown by the code `e.parentNode.replaceChild(i, e) `within the `lazyload-scripts.min.js` file.

**WP Rocket Version:** 3.13.2

**Comment by piotrbak** [comment]
Hello @devendrabhandari could you confirm that the issue happens on 3.15.9 too?

**Comment by devendrabhandari** [comment]
Hello @piotrbak 
Yes, I have updated the WP Rocket version to **3.15.9** and the issue still persists.
Thanks

**Comment by piotrbak** [comment]
@devendrabhandari Have you tried solution mentioned in this comment?
https://github.com/wp-media/wp-rocket/issues/3086#issuecomment-701560825

**Comment by devendrabhandari** [comment]
@piotrbak 
Yes, it didn't work. To replicate the issue, add a nonce to the script-src directive in the CSP and then include the nonce in the inline script. Test it on Firefox to observe the issue.

**Comment by piotrbak** [comment]
@devendrabhandari If you could, please contact our Support Team and provide access to the template, we'll check what's going on.

**Comment by devendrabhandari** [comment]
@piotrbak Ok, thank you.

**Comment by piotrbak** [comment]
@devendrabhandari Could you provide us the exact CSP rules you're using?

**Comment by gfirem** [comment]
This is happening to a client website now with the last version of wp-rocket
