### ISSUE TITLE
Auto-Apply Delay JS per Page/Post Type

### ISSUE THREAD

**Issue by pdfrequest3** [wp-media/wp-rocket#4177]
**Is your feature request related to a problem? Please describe.**
I have around 300 Product Pages and I want to go in to edit on each of the Product Pages one by one to disable Delay JS Checkbox, which is very tiresome. 

![image](https://user-images.githubusercontent.com/72587161/126245834-5ddf45b4-4d8c-4f6f-a568-7a2863ec0f03.png)

**Describe the solution you'd like**
A checkbox should be selected (one or more selections) as to what type of pages/posts will the Delay Javascript be applied/enabled. Whether it be Blog Posts, Pages, Archive Pages, Product Pages etc.

![image](https://user-images.githubusercontent.com/72587161/126245931-556ff87b-d4a9-4328-a657-f278d057e99b.png)

@GeekPress , Would It be nice to have this feature?

**Comment by gevcen** [comment]
Are your products classified by product catégories? Why dont you add the slugs/path url of your categories in the Exclusion box? Isnt this an easy way to solve this issue?

**Comment by pdfrequest3** [comment]
> Are your products classified by product catégories? Why dont you add the slugs/path url of your categories in the Exclusion box? Isnt this an easy way to solve this issue?

@gevcen I think the path urls only refer to urls to the actual js files and not urls of the pages. I even tried adding "/product/" to the exclusion list -- doesn't work.

![image](https://user-images.githubusercontent.com/72587161/126324976-f936f76b-b926-497e-90fd-c8f0b8a3ac4c.png)

**Comment by gevcen** [comment]
@pdfrequest3 
No. You can perfectly add a path URL (without necessarily mentionning the js file itself)
You must ensure that your products are using the /product/ in case you've assigned custom permalink paths.
Try adding the product categories slug there, and it should solve this.

**Comment by pdfrequest3** [comment]
> @pdfrequest3
> No. You can perfectly add a path URL (without necessarily mentionning the js file itself)
> You must ensure that your products are using the /product/ in case you've assigned custom permalink paths.
> Try adding the product categories slug there, and it should solve this.

@gevcen My URLs are patterned this way:

https://site.com/product-category/2011/
https://site.com/product-category/2011/dodge-2011/
https://site.com/product-category/2011/dodge-2011/ram-1500-dodge-2011/
https://site.com/product/dodge-ram-tipm-part-04692319-rebuilt/

I add these URLs to the exclusion list, still won't work.

/product-category/2011/
/product-category/2011/dodge-2011/
/product-category/2011/dodge-2011/ram-1500-dodge-2011/
/product/dodge-ram-tipm-part-04692319-rebuilt/

Also, I have around 300 products. So listing all 300+ in the exclusion list is 😐

**Comment by DahmaniAdame** [comment]
@pdfrequest3 you can disable options programmatically using the helper plugin found on this page: 

https://docs.wp-rocket.me/article/1561-programmatically-toggle-wp-rocket-options-under-specific-conditions

The default values of the helper plugin will disable Delay JavaScript Execution on product pages.

**Comment by pdfrequest3** [comment]
@DahmaniAdame , This one worked for me. But not everyone will be comfortable using this approach. Also, quite few already upvoted for this feature on the WP Rocket Feedback Page: https://feedback.wp-rocket.me/68

**Comment by piotrbak** [comment]
We didn't have any further feedbacks that would justify including that kind of feature in the UI. I'm going to close it and if there'll be a good reason to add it to the UI, we'll reopen.
