### ISSUE TITLE
[WIP] RUCSS - fixed issues resurface after WP Rocket's update

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4548]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅`3.10.4`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

We have reports from customers about Remove Unused CSS-related issues resurfacing, e.g. after a WP Rocket update. 

Usually, the story goes like this. The customer contacted us to resolve an issue, e.g. the mobile menu wasn't working. We fixed that and everything was working as expected until, usually after a WP Rocket update, the issue resurfaces. In most of the cases, it was impossible to reproduce the issue, when we tried.

This thread is to monitor such issues and try to document what caused them.

**To Reproduce**
Not relevant.

**Related tickets:**

https://secure.helpscout.net/conversation/1691713445/306772/
https://secure.helpscout.net/conversation/1710986022/311283/
https://secure.helpscout.net/conversation/1707446454/310279/
https://secure.helpscout.net/conversation/1709950259/310948/

**Slack convo:** https://wp-media.slack.com/archives/C029G1B5HD2/p1638189111004400

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alfonso100** [comment]
Related: https://secure.helpscout.net/conversation/1712436600/311647?folderId=2683093

**Comment by alfonso100** [comment]
Another case: 
https://secure.helpscout.net/conversation/1712436600/311647?folderId=273766

According to the customer, the production site was affected. 
I wasn't able to reproduce it after updating from 3.10.3 to 3.10.4 on the Dev site.

going back to Production, the customer deactivated RUCSS. After reactivating it, the exclusions were taken into consideration again and the issue was solved.

**Comment by DahmaniAdame** [comment]
Possibly related - https://secure.helpscout.net/conversation/1709706235/310902/
Menu not working after updates.
Testing downgrade/upgrade didn't trigger the issue.
Waiting for the customer to catch the next occurrence to investigate further.

**Comment by webtrainingwheels** [comment]
Probably related:  https://secure.helpscout.net/conversation/1715312840/312326/
RUCSS working fine, without any exclusions. 
Customer updates from 3.10.3 → 3.10.4 and suddenly some things are broken and resolved when disabling RUCSS. Did not see any unprocessed CSS files. 
Rolled back, issue still exists. Updated again to 3.10.4, issue magically resolves itself at some point.

**Comment by alfonso100** [comment]
Probably related: 
https://secure.helpscout.net/conversation/1719291270/313032

RUCSS issues previously fixed, resurfaced after a WP Rocket update. 
The customer fixed it by deactivating/reactivating the feature

**Comment by vmanthos** [comment]
@piotrbak This is about the old RUCSS. I'm closing it.
