### ISSUE TITLE
Unable to generate Critical CSS

### ISSUE THREAD

**Issue by simkoG** [wp-media/wp-rocket#5891]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
The Critical CSS generation timed out on every website since yesterday. There was no error before yesterday. I've tried with two different web servers both have the same error.

**To Reproduce**
1. Activate "Optimize CSS delivery."
2. Run "Regenerate Critical CSS." 
3. See the error message at the top of the page. 

**Expected behavior**
Run the Optimize CSS delivery succesfully. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10430702/235100442-fbe11126-cfaa-483d-8435-bb430440b150.png)

**Additional context**
```
### wp-core ###

version: 6.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/rituresoma4085/web/restaurant-heza.instawp.xyz/public_html
wordpress_size: 50.70 MB (53166682 bytes)
uploads_path: /home/rituresoma4085/web/restaurant-heza.instawp.xyz/public_html/wp-content/uploads
uploads_size: 13.00 B (13 bytes)
themes_path: /home/rituresoma4085/web/restaurant-heza.instawp.xyz/public_html/wp-content/themes
themes_size: 2.51 MB (2630071 bytes)
plugins_path: /home/rituresoma4085/web/restaurant-heza.instawp.xyz/public_html/wp-content/plugins
plugins_size: 13.35 MB (14003004 bytes)
database_size: 2.50 MB (2621440 bytes)
total_size: 69.07 MB (72421210 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Twenty Twenty-Three (twentytwentythree)
version: 1.1
author: the WordPress team
author_website: https://wordpress.org
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor
theme_path: /home/rituresoma4085/web/restaurant-heza.instawp.xyz/public_html/wp-content/themes/twentytwentythree

### wp-plugins-active (2) ###

HelloPack: version: 1.2.20, author: HelloWP Ltd
WP Rocket: version: 3.13.1, author: WP Media

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 1.844674407371E+19
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.4.0-122-generic x86_64
httpd_software: Apache/2.4.56 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
php_version: 7.4.33 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.11.2-MariaDB-1:10.11.2+maria~ubu2004
client_version: mysqlnd 7.4.33
max_allowed_packet: 33554432
max_connections: 200

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/rituresoma4085/web/restaurant-heza.instawp.xyz/public_html/wp-content
WP_PLUGIN_DIR: /home/rituresoma4085/web/restaurant-heza.instawp.xyz/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 256M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
It should be solved now.

**Comment by smerriman** [comment]
@engahmeds3ed This is not resolved at all. Critical CSS is still failing to regenerate on my sites with the same error as mentioned above.

**Comment by idmahbub** [comment]
<img width="673" alt="Screen Shot 2023-05-02 at 06 44 44" src="https://user-images.githubusercontent.com/2823242/235552030-a8d9e3a1-d728-4fae-9367-bdfc005ce2db.png">
I tried it by calling direct api to generate critical css, out of 10 tests only 2 were successful, the others were stuck with a "generating" status like the picture above.

**Comment by simkoG** [comment]
Yes, the error still exists.

![image](https://user-images.githubusercontent.com/10430702/235598496-213d76c2-befa-4147-8723-da2b05bade1f.png)

**Comment by lestertarranza** [comment]
![image](https://user-images.githubusercontent.com/4747198/235820578-28ab0dda-ee9d-4c8f-b8a7-8ecc525c2b48.png)
Same thing on our sites.

**Comment by androidacy-user** [comment]
> It should be solved now.

This issue is still very much not solved, months later. RUCSS is not an option for us as it kills BS5 background colors that use `rgb()`
