### ISSUE TITLE
Update DelayJS to v2

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#7092]
DelayJS v2 must be released on WP Rocket.
The "v2" is currently available on the "v2" branch of the delay JS repo.

Here is the process to automatically update WP Rocket with a DelayJS release: https://www.notion.so/wpmedia/Maintaining-JavaScript-files-98e4112922d540da93e2536866e36fd8?pvs=4#95bb73a9447745228d1c6376e5ad3732

**Comment by wordpressfan** [comment]
I found [this PR](https://github.com/wp-media/delay-javascript-loading/pull/125) to merge v2 into develop then we can merge develop into main and release from main but I can see some conflicts, let me check if we can resolve the conflicts from our side or we will need to check with Gael.

**Comment by MathieuLamiot** [comment]
@wordpressfan This has already been discussed with Gael here: https://wp-media.slack.com/archives/CUT7FLHF1/p1729614432850799?thread_ts=1729184313.104719&cid=CUT7FLHF1

**Comment by wordpressfan** [comment]
Awesome, so we will ignore conflicts and keep the v2 changes.

**Comment by Mai-Saad** [comment]
Waiting feedback for possible regression https://wp-media.slack.com/archives/CUT7FLHF1/p1731051322877729?thread_ts=1729184313.104719&cid=CUT7FLHF1

**Comment by Mai-Saad** [comment]
Regression list

- [x] clicking links on FF will load scripts before doing further interaction (using tab to open link is fine) https://wpmediaqa.testrail.io/index.php?/tests/view/44270&group_by=cases:section_id&group_id=4884&group_order=asc
- [x] double tap needed for menu to open with certain template https://wp-media.slack.com/archives/CUT7FLHF1/p1731402244073589?thread_ts=1729184313.104719&cid=CUT7FLHF1
- [x] clicking the link, we sometimes will see nothing is delayed on chrome/FF https://wp-media.slack.com/archives/CUT7FLHF1/p1731051322877729?thread_ts=1729184313.104719&cid=CUT7FLHF1

non-regression 
- open page from saved tab loads all script without further interaction (even on 3.17.2.1 of wpr, so maybe browser changes is a factor)
https://wpmediaqa.testrail.io/index.php?/tests/view/44269&group_by=cases:section_id&group_id=4884&group_order=asc
- this issue related to safari double click is still there https://github.com/wp-media/wp-rocket/issues/3142

**Comment by piotrbak** [comment]
CC @gmetais

**Comment by gmetais** [comment]
Hi @Mai-Saad,

Could you please describe this issue a bit more? 

> open page from saved tab loads all script without further interaction (even on 3.17.2.1 of wpr, so maybe browser changes is a factor)
https://wpmediaqa.testrail.io/index.php?/tests/view/44269&group_by=cases:section_id&group_id=4884&group_order=asc

What is a saved tab? Is it related to the fact that DelayJS intentionally loads scripts when the page [visibility](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) is hidden?

**Comment by Mai-Saad** [comment]
@gmetais Here is a video about the saved tab (usually scripts aren't delayed there)
[saved pages.zip](https://github.com/user-attachments/files/17832493/saved.pages.zip)

**Comment by piotrbak** [comment]
@gmetais Were you able to take a look at this?

**Comment by gmetais** [comment]
@piotrbak Not yet, I will investigate deeper all the issues reported above this Friday.

(As far as I see, none of them look hard to solve. I'm confident for the moment. 🤞)

**Comment by gmetais** [comment]
Hi @Mai-Saad,

A fix for 

> clicking links on FF will load scripts before doing further interaction (using tab to open link is fine) https://wpmediaqa.testrail.io/index.php?/tests/view/44270&group_by=cases:section_id&group_id=4884&group_order=asc

was merged into DelayJS `main` branch (see PR https://github.com/wp-media/delay-javascript-loading/pull/137/)

**Comment by gmetais** [comment]
@Mai-Saad,

Also please confirm it fixes this:

> clicking the link, we sometimes will see nothing is delayed on chrome/FF https://wp-media.slack.com/archives/CUT7FLHF1/p1731051322877729?thread_ts=1729184313.104719&cid=CUT7FLHF1

**Comment by gmetais** [comment]
Regarding 

> double tap needed for menu to open with certain template https://wp-media.slack.com/archives/CUT7FLHF1/p1731402244073589?thread_ts=1729184313.104719&cid=CUT7FLHF1

I have contacted Hanna in private to provide a testing env.

**Comment by gmetais** [comment]
> [@gmetais](https://github.com/gmetais) Here is a video about the saved tab (usually scripts aren't delayed there) [saved pages.zip](https://github.com/user-attachments/files/17832493/saved.pages.zip)

@Mai-Saad,

DelayJS is currently disabled on the page URL in your video. I've tried with some other pages but couldn't reproduce. I'd be interested in having the environment set up fine, for me to investigate the issue.

**Comment by Mai-Saad** [comment]
>I have contacted Hanna in private to provide a testing env.

@gmetais Any updates about this one? 🙏

**Comment by gmetais** [comment]
Hi @Mai-Saad,
I'm able to reproduce and I'm investigating, but this one is not an easy bug.

**Comment by gmetais** [comment]
@Mai-Saad, @hanna-meda, @piotrbak,

I have a fix for the issue "double tap needed for menu to open with certain template", I pushed it on the following branch: https://github.com/wp-media/delay-javascript-loading/tree/fix-ios-click

Some quick information related to this bug. Safari has a really strange behavior that seems to prevent the first `click` event from being fired. A `touchstart` event is fired, a `touchend` event too, but no `click`. For the moment, I don't understand why it works on some pages and not the others.

The fix I found is as weird as the bug itself. Adding an `addEventListener('click', function() {})` to the `touchstart` targeted element, solves the issue, even with an empty callback. At least it works on an iOS 15.8 iPhone.

I note that some developers had already found some similarly strange fixes for the iOS double click issue:

- [here](https://github.com/wp-media/wp-rocket/issues/3142#issuecomment-1899980159) with an empty callback,
- [here](https://github.com/wp-media/wp-rocket/issues/3142#issuecomment-1870722927) with an algorithm that triggers a `click` if a `touchstart` and a `touchend` are detected.

I will try to find the deeper reason for this bug, but in the meanwhile I think that the version published on the above branch is a good candidate for production (the change is low-risky). Could you please test on your side?

**Comment by hanna-meda** [comment]
@gmetais, thank you once again. This is indeed a capricious bug! Below are the testing results:

Tested on BrowserStack (real devices):
	•	iPhone 12 Pro (iOS 18): Working most of the time.
	•	iPhone 15 (iOS 17): Works every other try.
	•	iPhone 14 Pro (iOS 16): Worked on the first try, but failed in over 10 subsequent attempts.
	•	iPhone 12 (iOS 15): Working occasionally.

Tested on personal device:
	•	iPhone SE (2nd gen, iOS 18.1.1): Works intermittently.

Conclusion:
Behavior has improved but is not 100% reliable.

[Later edit] 
I double-checked the issue on djs version 1.2.6 (current trunk) across all the above devices and it is working consistently (10/10). 
@gmetais We need to ensure this isssue is addressed to prevent introducing a regression. 
cc @Mai-Saad, @piotrbak

**Comment by gmetais** [comment]
Thanks a lot @hanna-meda,

I still don't understand which change in DelayJS v2 introduced this regression, but it definitely looks like our old double click issue.

I've started working on a fix based on the idea here https://github.com/wp-media/wp-rocket/issues/3142#issuecomment-1870722927, but with additional securities to prevent clicks being triggered twice on websites that don't experience the bug. I will finish in January.

**Comment by gmetais** [comment]
Hi @hanna-meda,

I've updated the same branch (https://github.com/wp-media/delay-javascript-loading/tree/fix-ios-click) with a new approach for the fix and it is working fine on my test page and my test device. Do you mind making a new round of tests with the updated code please?

Cc. @Mai-Saad @piotrbak

**Comment by hanna-meda** [comment]
Hi @gmetais,

I'm sorry for bringing bad news again, but I’m still able to reproduce the issue on this page: https://rocketlabsqa.ovh/testing-djs-v2/.

I tested it on the following devices and stopped checking others, as the issue could be reproduced consistently:
• Personal device - iPhone SE (2nd gen, iOS 18.1.1)
• BrowserStack - iPhone 14 Pro (iOS 16)

**Comment by gmetais** [comment]
Thank you for your quick answer @hanna-meda. My last commit was assuming the bug was only happening on `<a>` or `<button>` elements, but your test site proves it can be anything. I've commited a change on the same branch and it should be working better now.

**Comment by hanna-meda** [comment]
Thank you, @gmetais. Good news this time: tested extensively on multiple devices and different versions of Safari/iOS, and the fix appears consistent, the menu expanded every time with the first tap. 

@piotrbak, @Mai-Saad, I believe this was the last remaining issue. Now that it’s fixed, we can resume testing the DJS v2 update.

**Comment by hanna-meda** [comment]
Thank you, @gmetais. Good news this time: tested extensively on multiple devices and different versions of Safari/iOS, and the fix appears consistent, the menu expanded every time with the first tap.

@piotrbak, @Mai-Saad, I believe this was the last remaining issue. Now that it’s fixed, we can resume testing the DJS v2 update.

**Comment by piotrbak** [comment]
@wp-media/engineering-team Could you update the script with the latest version from the Delay JS Script repository?

The tests were performed on it, the current version of the script on this PR is not up to date.

**Comment by wordpressfan** [comment]
Done @piotrbak
